name: build
on: [push]
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Ensure line endings are sane
        run: git config --global core.autocrlf input
      # Dependencies
      - name: Checkout project and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Cache Cygwin dependencies
        uses: actions/cache@v3
        with:
          path: |
            C:/cygwin-packages
          key: ${{ runner.os }}
      - name: Install Cygwin and dependencies
        uses: cygwin/cygwin-install-action@master
        with:
          packages: >-
            libtool
            make
            m4
            gcc-core
            gcc-g++
            libgcc1
            cmake
            libmpfr-devel
            libOpenCL1
            libboost-devel
            python3-devel

      # Actual work
      - name: Generate build info
        run: python3.9 build.py eigen
        working-directory: ./third_party
      - run: mkdir build
      - name: Run cmake
        run: cmake -DCMAKE_CXX_FLAGS="-fopenmp -std=gnu++0x -Wa,-mbig-obj -O3 -D_POSIX_C_SOURCE=200809L" ..
        working-directory: build
      - name: Run make
        run: make
        working-directory: build

      - name: Collect artifacts
        uses: actions/upload-artifact@v2
        with:
          path: build/*
